# server:
#   port: 3000

# spring:
#   datasource:
#     driverClassName: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://localhost:3306/microservice_db?createDatabaseIfNotExist=true
#     username: root
#     password: 
#   jpa:
#     hibernate:
#       ddlAuto: update
#     showSql: true
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.MySQLDialect
  #security:
  #  user:
  #    name: deep
  #    password: deep
  #    roles: ADMIN